; MonsterNames:
; 	db "RHYDON@@@@"
; 	db "KANGASKHAN"
; 	db "NIDORAN♂@@"
; 	db "CLEFAIRY@@"
; 	db "SPEAROW@@@"
; 	db "VOLTORB@@@"
; 	db "NIDOKING@@"
; 	db "SLOWBRO@@@"
; 	db "IVYSAUR@@@"
; 	db "EXEGGUTOR@"
; 	db "LICKITUNG@"
; 	db "EXEGGCUTE@"
; 	db "GRIMER@@@@"
; 	db "GENGAR@@@@"
; 	db "NIDORAN♀@@"
; 	db "NIDOQUEEN@"
; 	db "CUBONE@@@@"
; 	db "RHYHORN@@@"
; 	db "LAPRAS@@@@"
; 	db "ARCANINE@@"
; 	db "MEW@@@@@@@"
; 	db "GYARADOS@@"
; 	db "SHELLDER@@"
; 	db "TENTACOOL@"
; 	db "GASTLY@@@@"
; 	db "SCYTHER@@@"
; 	db "STARYU@@@@"
; 	db "BLASTOISE@"
; 	db "PINSIR@@@@"
; 	db "TANGELA@@@"
; 	db "MISSINGNO."
; 	db "MISSINGNO."
; 	db "GROWLITHE@"
; 	db "ONIX@@@@@@"
; 	db "FEAROW@@@@"
; 	db "PIDGEY@@@@"
; 	db "SLOWPOKE@@"
; 	db "KADABRA@@@"
; 	db "GRAVELER@@"
; 	db "CHANSEY@@@"
; 	db "MACHOKE@@@"
; 	db "MR.MIME@@@"
; 	db "HITMONLEE@"
; 	db "HITMONCHAN"
; 	db "ARBOK@@@@@"
; 	db "PARASECT@@"
; 	db "PSYDUCK@@@"
; 	db "DROWZEE@@@"
; 	db "GOLEM@@@@@"
; 	db "MISSINGNO."
; 	db "MAGMAR@@@@"
; 	db "MISSINGNO."
; 	db "ELECTABUZZ"
; 	db "MAGNETON@@"
; 	db "KOFFING@@@"
; 	db "MISSINGNO."
; 	db "MANKEY@@@@"
; 	db "SEEL@@@@@@"
; 	db "DIGLETT@@@"
; 	db "TAUROS@@@@"
; 	db "MISSINGNO."
; 	db "MISSINGNO."
; 	db "MISSINGNO."
; 	db "FARFETCH'D"
; 	db "VENONAT@@@"
; 	db "DRAGONITE@"
; 	db "MISSINGNO."
; 	db "MISSINGNO."
; 	db "MISSINGNO."
; 	db "DODUO@@@@@"
; 	db "POLIWAG@@@"
; 	db "JYNX@@@@@@"
; 	db "MOLTRES@@@"
; 	db "ARTICUNO@@"
; 	db "ZAPDOS@@@@"
; 	db "DITTO@@@@@"
; 	db "MEOWTH@@@@"
; 	db "KRABBY@@@@"
; 	db "MISSINGNO."
; 	db "MISSINGNO."
; 	db "MISSINGNO."
; 	db "VULPIX@@@@"
; 	db "NINETALES@"
; 	db "PIKACHU@@@"
; 	db "RAICHU@@@@"
; 	db "MISSINGNO."
; 	db "MISSINGNO."
; 	db "DRATINI@@@"
; 	db "DRAGONAIR@"
; 	db "KABUTO@@@@"
; 	db "KABUTOPS@@"
; 	db "HORSEA@@@@"
; 	db "SEADRA@@@@"
; 	db "MISSINGNO."
; 	db "MISSINGNO."
; 	db "SANDSHREW@"
; 	db "SANDSLASH@"
; 	db "OMANYTE@@@"
; 	db "OMASTAR@@@"
; 	db "JIGGLYPUFF"
; 	db "WIGGLYTUFF"
; 	db "EEVEE@@@@@"
; 	db "FLAREON@@@"
; 	db "JOLTEON@@@"
; 	db "VAPOREON@@"
; 	db "MACHOP@@@@"
; 	db "ZUBAT@@@@@"
; 	db "EKANS@@@@@"
; 	db "PARAS@@@@@"
; 	db "POLIWHIRL@"
; 	db "POLIWRATH@"
; 	db "WEEDLE@@@@"
; 	db "KAKUNA@@@@"
; 	db "BEEDRILL@@"
; 	db "MISSINGNO."
; 	db "DODRIO@@@@"
; 	db "PRIMEAPE@@"
; 	db "DUGTRIO@@@"
; 	db "VENOMOTH@@"
; 	db "DEWGONG@@@"
; 	db "MISSINGNO."
; 	db "MISSINGNO."
; 	db "CATERPIE@@"
; 	db "METAPOD@@@"
; 	db "BUTTERFREE"
; 	db "MACHAMP@@@"
; 	db "MISSINGNO."
; 	db "GOLDUCK@@@"
; 	db "HYPNO@@@@@"
; 	db "GOLBAT@@@@"
; 	db "MEWTWO@@@@"
; 	db "SNORLAX@@@"
; 	db "MAGIKARP@@"
; 	db "MISSINGNO."
; 	db "MISSINGNO."
; 	db "MUK@@@@@@@"
; 	db "MISSINGNO."
; 	db "KINGLER@@@"
; 	db "CLOYSTER@@"
; 	db "MISSINGNO."
; 	db "ELECTRODE@"
; 	db "CLEFABLE@@"
; 	db "WEEZING@@@"
; 	db "PERSIAN@@@"
; 	db "MAROWAK@@@"
; 	db "MISSINGNO."
; 	db "HAUNTER@@@"
; 	db "ABRA@@@@@@"
; 	db "ALAKAZAM@@"
; 	db "PIDGEOTTO@"
; 	db "PIDGEOT@@@"
; 	db "STARMIE@@@"
; 	db "BULBASAUR@"
; 	db "VENUSAUR@@"
; 	db "TENTACRUEL"
; 	db "MISSINGNO."
; 	db "GOLDEEN@@@"
; 	db "SEAKING@@@"
; 	db "MISSINGNO."
; 	db "MISSINGNO."
; 	db "MISSINGNO."
; 	db "MISSINGNO."
; 	db "PONYTA@@@@"
; 	db "RAPIDASH@@"
; 	db "RATTATA@@@"
; 	db "RATICATE@@"
; 	db "NIDORINO@@"
; 	db "NIDORINA@@"
; 	db "GEODUDE@@@"
; 	db "PORYGON@@@"
; 	db "AERODACTYL"
; 	db "MISSINGNO."
; 	db "MAGNEMITE@"
; 	db "MISSINGNO."
; 	db "MISSINGNO."
; 	db "CHARMANDER"
; 	db "SQUIRTLE@@"
; 	db "CHARMELEON"
; 	db "WARTORTLE@"
; 	db "CHARIZARD@"
; 	db "MISSINGNO."
; 	db "MISSINGNO."
; 	db "MISSINGNO."
; 	db "MISSINGNO."
; 	db "ODDISH@@@@"
; 	db "GLOOM@@@@@"
; 	db "VILEPLUME@"
; 	db "BELLSPROUT"
; 	db "WEEPINBELL"
; 	db "VICTREEBEL"

MonsterNames:
	db "钻角犀兽@@"
	db "袋兽@@@@@@"
	db "尼多朗@@@@"
	db "皮皮@@@@@@"
	db "烈雀@@@@@@"
	db "霹雳电球@@"
	db "尼多王@@@@"
	db "呆壳兽@@@@"
	db "妙蛙草@@@@"
	db "椰蛋树@@@@"
	db "大舌头@@@@"
	db "蛋蛋@@@@@@"
	db "臭泥@@@@@@"
	db "耿鬼@@@@@@"
	db "尼多兰@@@@"
	db "尼多后@@@@"
	db "卡拉卡拉@@"
	db "独角犀牛@@"
	db "拉普拉斯@@"
	db "风速狗@@@@"
	db "梦幻@@@@@@"
	db "暴鲤龙@@@@"
	db "大舌贝@@@@"
	db "玛瑙水母@@"
	db "鬼斯@@@@@@"
	db "飞天螳螂@@"
	db "海星星@@@@"
	db "水箭龟@@@@"
	db "凯罗斯@@@@"
	db "蔓藤怪@@@@"
	db "遗失编号@@"
	db "遗失编号@@"
	db "卡蒂狗@@@@"
	db "大岩蛇@@@@"
	db "大嘴雀@@@@"
	db "波波@@@@@@"
	; db "AAAAAAAAAA"
	db "呆呆兽@@@@"
	db "勇基拉@@@@"
	db "隆隆石@@@@"
	db "吉利蛋@@@@"
	db "豪力@@@@@@"
	db "魔墙人偶@@"
	db "飞腿郎@@@@"
	db "快拳郎@@@@"
	db "阿柏怪@@@@"
	db "派拉斯特@@"
	db "可达鸭@@@@"
	db "催眠貘@@@@"
	db "隆隆岩@@@@"
	db "遗失编号@@"
	db "鸭嘴火兽@@"
	db "遗失编号@@"
	db "电击兽@@@@"
	db "三合一磁怪"
	db "瓦斯弹@@@@"
	db "遗失编号@@"
	db "猴怪@@@@@@"
	db "小海狮@@@@"
	db "地鼠@@@@@@"
	db "肯泰罗@@@@"
	db "遗失编号@@"
	db "遗失编号@@"
	db "遗失编号@@"
	db "大葱鸭@@@@"
	db "毛球@@@@@@"
	db "快龙@@@@@@"
	db "遗失编号@@"
	db "遗失编号@@"
	db "遗失编号@@"
	db "嘟嘟@@@@@@"
	db "蚊香蝌蚪@@"
	db "迷唇姐@@@@"
	db "火焰鸟@@@@"
	db "急冻鸟@@@@"
	db "闪电鸟@@@@"
	db "百变怪@@@@"
	db "喵喵@@@@@@"
	db "大钳蟹@@@@"
	db "遗失编号@@"
	db "遗失编号@@"
	db "遗失编号@@"
	db "六尾@@@@@@"
	db "九尾@@@@@@"
	db "皮卡丘@@@@"
	db "雷丘@@@@@@"
	db "遗失编号@@"
	db "遗失编号@@"
	db "迷你龙@@@@"
	db "哈克龙@@@@"
	db "化石盔@@@@"
	db "镰刀盔@@@@"
	db "墨海马@@@@"
	db "海刺龙@@@@"
	db "遗失编号@@"
	db "遗失编号@@"
	db "穿山鼠@@@@"
	db "穿山王@@@@"
	db "菊石兽@@@@"
	db "多刺菊石兽"
	db "胖丁@@@@@@"
	db "胖可丁@@@@"
	db "伊布@@@@@@"
	db "火伊布@@@@"
	db "雷伊布@@@@"
	db "水伊布@@@@"
	db "腕力@@@@@@"
	db "超音蝠@@@@"
	db "阿柏蛇@@@@"
	db "派拉斯@@@@"
	db "蚊香君@@@@"
	db "蚊香泳士@@"
	db "独角虫@@@@"
	db "铁壳蛹@@@@"
	db "大针蜂@@@@"
	db "遗失编号@@"
	db "嘟嘟利@@@@"
	db "火暴猴@@@@"
	db "三地鼠@@@@"
	db "摩鲁蛾@@@@"
	db "白海狮@@@@"
	db "遗失编号@@"
	db "遗失编号@@"
	db "绿毛虫@@@@"
	db "铁甲蛹@@@@"
	db "巴大蝶@@@@"
	db "怪力@@@@@@"
	db "遗失编号@@"
	db "哥达鸭@@@@"
	db "引梦貘人@@"
	db "大嘴蝠@@@@"
	db "超梦@@@@@@"
	db "卡比兽@@@@"
	db "鲤鱼王@@@@"
	db "遗失编号@@"
	db "遗失编号@@"
	db "臭臭泥@@@@"
	db "遗失编号@@"
	db "巨钳蟹@@@@"
	db "刺甲贝@@@@"
	db "遗失编号@@"
	db "顽皮雷弹@@"
	db "皮可西@@@@"
	db "双弹瓦斯@@"
	db "猫老大@@@@"
	db "嘎啦嘎啦@@"
	db "遗失编号@@"
	db "鬼斯通@@@@"
	db "凯西@@@@@@"
	db "胡地@@@@@@"
	db "比比鸟@@@@"
	db "大比鸟@@@@"
	db "宝石海星@@"
	db "妙蛙种子@@"
	db "妙蛙花@@@@"
	db "毒刺水母@@"
	db "遗失编号@@"
	db "角金鱼@@@@"
	db "金鱼王@@@@"
	db "遗失编号@@"
	db "遗失编号@@"
	db "遗失编号@@"
	db "遗失编号@@"
	db "小火马@@@@"
	db "烈焰马@@@@"
	db "小拉达@@@@"
	db "拉达@@@@@@"
	db "尼多力诺@@"
	db "尼多娜@@@@"
	db "小拳石@@@@"
	db "多边兽@@@@"
	db "化石翼龙@@"
	db "遗失编号@@"
	db "小磁怪@@@@"
	db "遗失编号@@"
	db "遗失编号@@"
	db "小火龙@@@@"
	db "杰尼龟@@@@"
	db "火恐龙@@@@"
	db "卡咪龟@@@@"
	db "喷火龙@@@@"
	db "遗失编号@@"
	db "遗失编号@@"
	db "遗失编号@@"
	db "遗失编号@@"
	db "走路草@@@@"
	db "臭臭花@@@@"
	db "霸王花@@@@"
	db "喇叭芽@@@@"
	db "口呆花@@@@"
	db "大食花@@@@"