MoveNames::
	; db "POUND@"
	; db "KARATE CHOP@"
	; db "DOUBLESLAP@"
	; db "COMET PUNCH@"
	; db "MEGA PUNCH@"
	; db "PAY DAY@"
	; db "FIRE PUNCH@"
	; db "ICE PUNCH@"
	; db "THUNDERPUNCH@"
	; db "SCRATCH@"
	; db "VICEGRIP@"
	; db "GUILLOTINE@"
	; db "RAZOR WIND@"
	; db "SWORDS DANCE@"
	; db "CUT@"
	; db "GUST@"
	; db "WING ATTACK@"
	; db "WHIRLWIND@"
	; db "FLY@"
	; db "BIND@"
	; db "SLAM@"
	; db "VINE WHIP@"
	; db "STOMP@"
	; db "DOUBLE KICK@"
	; db "MEGA KICK@"
	; db "JUMP KICK@"
	; db "ROLLING KICK@"
	; db "SAND-ATTACK@"
	; db "HEADBUTT@"
	; db "HORN ATTACK@"
	; db "FURY ATTACK@"
	; db "HORN DRILL@"
	; db "TACKLE@"
	; db "BODY SLAM@"
	; db "WRAP@"
	; db "TAKE DOWN@"
	; db "THRASH@"
	; db "DOUBLE-EDGE@"
	; db "TAIL WHIP@"
	; db "POISON STING@"
	; db "TWINEEDLE@"
	; db "PIN MISSILE@"
	; db "LEER@"
	; db "BITE@"
	; db "GROWL@"
	; db "ROAR@"
	; db "SING@"
	; db "SUPERSONIC@"
	; db "SONICBOOM@"
	; db "DISABLE@"
	; db "ACID@"
	; db "EMBER@"
	; db "FLAMETHROWER@"
	; db "MIST@"
	; db "WATER GUN@"
	; db "HYDRO PUMP@"
	; db "SURF@"
	; db "ICE BEAM@"
	; db "BLIZZARD@"
	; db "PSYBEAM@"
	; db "BUBBLEBEAM@"
	; db "AURORA BEAM@"
	; db "HYPER BEAM@"
	; db "PECK@"
	; db "DRILL PECK@"
	; db "SUBMISSION@"
	; db "LOW KICK@"
	; db "COUNTER@"
	; db "SEISMIC TOSS@"
	; db "STRENGTH@"
	; db "ABSORB@"
	; db "MEGA DRAIN@"
	; db "LEECH SEED@"
	; db "GROWTH@"
	; db "RAZOR LEAF@"
	; db "SOLARBEAM@"
	; db "POISONPOWDER@"
	; db "STUN SPORE@"
	; db "SLEEP POWDER@"
	; db "PETAL DANCE@"
	; db "STRING SHOT@"
	; db "DRAGON RAGE@"
	; db "FIRE SPIN@"
	; db "THUNDERSHOCK@"
	; db "THUNDERBOLT@"
	; db "THUNDER WAVE@"
	; db "THUNDER@"
	; db "ROCK THROW@"
	; db "EARTHQUAKE@"
	; db "FISSURE@"
	; db "DIG@"
	; db "TOXIC@"
	; db "CONFUSION@"
	; db "PSYCHIC@"
	; db "HYPNOSIS@"
	; db "MEDITATE@"
	; db "AGILITY@"
	; db "QUICK ATTACK@"
	; db "RAGE@"
	; db "TELEPORT@"
	; db "NIGHT SHADE@"
	; db "MIMIC@"
	; db "SCREECH@"
	; db "DOUBLE TEAM@"
	; db "RECOVER@"
	; db "HARDEN@"
	; db "MINIMIZE@"
	; db "SMOKESCREEN@"
	; db "CONFUSE RAY@"
	; db "WITHDRAW@"
	; db "DEFENSE CURL@"
	; db "BARRIER@"
	; db "LIGHT SCREEN@"
	; db "HAZE@"
	; db "REFLECT@"
	; db "FOCUS ENERGY@"
	; db "BIDE@"
	; db "METRONOME@"
	; db "MIRROR MOVE@"
	; db "SELFDESTRUCT@"
	; db "EGG BOMB@"
	; db "LICK@"
	; db "SMOG@"
	; db "SLUDGE@"
	; db "BONE CLUB@"
	; db "FIRE BLAST@"
	; db "WATERFALL@"
	; db "CLAMP@"
	; db "SWIFT@"
	; db "SKULL BASH@"
	; db "SPIKE CANNON@"
	; db "CONSTRICT@"
	; db "AMNESIA@"
	; db "KINESIS@"
	; db "SOFTBOILED@"
	; db "HI JUMP KICK@"
	; db "GLARE@"
	; db "DREAM EATER@"
	; db "POISON GAS@"
	; db "BARRAGE@"
	; db "LEECH LIFE@"
	; db "LOVELY KISS@"
	; db "SKY ATTACK@"
	; db "TRANSFORM@"
	; db "BUBBLE@"
	; db "DIZZY PUNCH@"
	; db "SPORE@"
	; db "FLASH@"
	; db "PSYWAVE@"
	; db "SPLASH@"
	; db "ACID ARMOR@"
	; db "CRABHAMMER@"
	; db "EXPLOSION@"
	; db "FURY SWIPES@"
	; db "BONEMERANG@"
	; db "REST@"
	; db "ROCK SLIDE@"
	; db "HYPER FANG@"
	; db "SHARPEN@"
	; db "CONVERSION@"
	; db "TRI ATTACK@"
	; db "SUPER FANG@"
	; db "SLASH@"
	; db "SUBSTITUTE@"
	; db "STRUGGLE@"

	db "拍击@"
	db "空手劈@"
	db "连环巴掌@"
	db "连续拳@"
	db "百万吨重拳@"
	db "聚宝功@"
	db "火焰拳@"
	db "冰冻拳@"
	db "雷电拳@"
	db "抓@"
	db "夹住@"
	db "断头钳@"
	db "旋风刀@"
	db "剑舞@"
	db "居合斩@"
	db "起风@"
	db "翅膀攻击@"
	db "吹飞@"
	db "飞翔@"
	db "绑紧@"
	db "摔打@"
	db "藤鞭@"
	db "踩踏@"
	db "二连踢@"
	db "百万吨重踢@"
	db "飞踢@"
	db "回旋踢@"
	db "泼沙@"
	db "头锤@"
	db "角撞@"
	db "乱击@"
	db "角钻@"
	db "撞击@"
	db "泰山压顶@"
	db "紧束@"
	db "猛撞@"
	db "大闹一番@"
	db "舍身冲撞@"
	db "摇尾巴@"
	db "毒针@"
	db "双针@"
	db "飞弹针@"
	db "瞪眼@"
	db "咬住@"
	db "叫声@"
	db "吼叫@"
	db "唱歌@"
	db "超音波@"
	db "音爆@"
	db "定身法@"
	db "溶解液@"
	db "火花@"
	db "喷射火焰@"
	db "白雾@"
	db "水枪@"
	db "水炮@"
	db "冲浪@"
	db "冰冻光束@"
	db "暴风雪@"
	db "幻象光线@"
	db "泡沫光线@"
	db "极光束@"
	db "破坏光线@"
	db "啄@"
	db "啄钻@"
	db "地狱翻滚@"
	db "踢倒@"
	db "双倍奉还@"
	db "地球上投@"
	db "怪力@"
	db "吸取@"
	db "超级吸取@"
	db "寄生种子@"
	db "生长@"
	db "飞叶快刀@"
	db "日光束@"
	db "毒粉@"
	db "麻痹粉@"
	db "催眠粉@"
	db "花瓣舞@"
	db "吐丝@"
	db "龙之怒@"
	db "火焰旋涡@"
	db "电击@"
	db "十万伏特@"
	db "电磁波@"
	db "打雷@"
	db "落石@"
	db "地震@"
	db "地裂@"
	db "挖洞@"
	db "剧毒@"
	db "念力@"
	db "精神强念@"
	db "催眠术@"
	db "瑜伽姿势@"
	db "高速移动@"
	db "电光一闪@"
	db "愤怒@"
	db "瞬间移动@"
	db "黑夜魔影@"
	db "模仿@"
	db "刺耳声@"
	db "影子分身@"
	db "自我再生@"
	db "变硬@"
	db "变小@"
	db "烟幕@"
	db "奇异之光@"
	db "缩入壳中@"
	db "变圆@"
	db "屏障@"
	db "光墙@"
	db "黑雾@"
	db "反射壁@"
	db "聚气@"
	db "忍耐@"
	db "挥指@"
	db "鹦鹉学舌@"
	db "自爆@"
	db "炸蛋@"
	db "舌舔@"
	db "浊雾@"
	db "污泥攻击@"
	db "骨棒@"
	db "大字爆炎@"
	db "攀瀑@"
	db "贝壳夹击@"
	db "高速星星@"
	db "火箭头锤@"
	db "尖刺加农炮@"
	db "缠绕@"
	db "瞬间失忆@"
	db "折弯汤匙@"
	db "生蛋@"
	db "飞膝踢@"
	db "大蛇瞪眼@"
	db "食梦@"
	db "毒瓦斯@"
	db "投球@"
	db "吸血@"
	db "恶魔之吻@"
	db "神鸟猛击@"
	db "变身@"
	db "泡沫@"
	db "迷昏拳@"
	db "蘑菇孢子@"
	db "闪光@"
	db "精神波@"
	db "跃起@"
	db "溶化@"
	db "蟹钳锤@"
	db "大爆炸@"
	db "乱抓@"
	db "骨头回力镖@"
	db "睡觉@"
	db "岩崩@"
	db "必杀门牙@"
	db "棱角化@"
	db "纹理@"
	db "三重攻击@"
	db "愤怒门牙@"
	db "劈开@"
	db "替身@"
	db "挣扎@"